# Configuración inicial para el ejercicio 4
corridas = 5

[data]
x = "data/paridad_x.txt"
y = "data/paridad_y.txt"
perc_train = 0.7
perc_test = 0.2

[architecture]
layers=[
    {activation_function="cosine", dims_in=1, dims_out=1},
    {activation_function="sigmoid", dims_in=1, dims_out=2},
]

w_distribution = "normal"
w_loc   = 3.14
w_scale = 1.0

b_distribution = "normal"
b_loc   = 0
b_scale = 0

[optimizer]
name = "Adam"

[train]
epochs = 200
batch_size = 10

[output]
folder = "out/ejercicio_3_paridad_std 1"
