# Configuración inicial para el ejercicio 4
corridas = 10

[data]
x = "data/mnist_x.txt"
y = "data/mnist_y.txt"
perc_train = 0.7
perc_test = 0.2

[architecture]
layers=[
    {activation_function="sigmoid", dims_in=64, dims_out=15},
    {activation_function="sigmoid", dims_in=15, dims_out=10},
]

w_distribution = "normal"
w_loc   = 0.0
w_scale = 0.1

b_distribution = "uniform"
b_low   = 0.0
b_high  = 0.0

[optimizer]
name = "SGD"
learning_rate = 0.001

[train]
epochs = 200
batch_size = 10

[output]
folder = "out/ejercicio_4_config00_sgd"
