# Configuración inicial para el ejercicio 4
corridas = 1

[data]
x = "data/xor_x.txt"
y = "data/xor_y.txt"
perc_train = 0.7
perc_test = 0.2

[architecture]
layers=[
    {activation_function="sigmoid", dims_in=2, dims_out=2},
    {activation_function="sigmoid", dims_in=2, dims_out=2},
]

w_distribution = "uniform"
w_low   = 0.0
w_high  = 1.0

b_distribution = "uniform"
b_low   = 0.0
b_high  = 1.0

[optimizer]
name = "Adam"


[train]
epochs = 200
batch_size = 1

[output]
folder = "out/ejercicio_3_xor_no lineal 2n"
